APP_NAME = "RemoteQBT"
QBITTORRENT_VERSION = "5.2.3"
REMOTEQBT_REVISION = 3
GITHUB_REPOSITORY = "FrederickCampbell/RemoteQBT"

RELEASE_ID = f"{QBITTORRENT_VERSION}-r{REMOTEQBT_REVISION}"
RELEASE_TAG = f"qbt-{RELEASE_ID}"
DISPLAY_VERSION = f"for qBittorrent {QBITTORRENT_VERSION} (r{REMOTEQBT_REVISION})"
